language: node_js
os:
  - linux
  - windows
  - osx
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
env:
  - NODE_ENV="test"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; chmod +x ./cc-test-reporter; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; ./cc-test-reporter before-build; fi
script:
  - npm run lint
  - npm run build
  - npm run coveralls
after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; ./cc-test-reporter after-build -t lcov ./coverage/*.json; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; ./cc-test-reporter upload-coverage; fi
