environment:
  matrix:
    - nodejs_version: "6.14"
    - nodejs_version: "7.10"
    - nodejs_version: "8.12"
cache:
  - node_modules
install:
  - npm install
build: off
test_script:
  - npm run lint
  - npm run build
  - npm run cover
version: "{build}"
