version: '3.4'
services:
  nginx:
    image: nginx:latest@sha256:56bcd35e8433343dbae0484ed5b740843dd8bff9479400990f251c13bbb94763
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server/nginx/nginx.api.conf:/etc/nginx/conf.d/api.conf
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: default.Dockerfile
    container_name: apiblackList
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - PG_USER_NAME=pguser
      - PG_PASS=pguser
      - PG_DB=db
      - PG_SCHEMA=public
      - PG_HOST=postgres
      - PG_PORT=5432
    ports:
      - 9229:9229
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:latest@sha256:3688892dcd09447e94ec393502eb7bb56d6280af479fd7aa694ce9431e2f9bb3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: db
      TZ: "America/Sao_Paulo"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
volumes:
  postgres-data:
