version: '3.4'
services:
  nginx:
    image: nginx:latest@sha256:b543f6d0983fbc25b9874e22f4fe257a567111da96fd1d8f1b44315f1236398c
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server/nginx/nginx.api.conf:/etc/nginx/conf.d/api.conf
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: default.Dockerfile
    container_name: apiblackList
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - PG_USER_NAME=pguser
      - PG_PASS=pguser
      - PG_DB=db
      - PG_SCHEMA=public
      - PG_HOST=postgres
      - PG_PORT=5432
    ports:
      - 9229:9229
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:latest@sha256:a195e4d9c43ea58ab114275ceccae112fbfab938567059a9d709548a51ee1e96
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: db
      TZ: "America/Sao_Paulo"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
volumes:
  postgres-data:
