AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Blacklist Aplication Serverless"
Globals:
  Function:
    Timeout: 30
Resources:
  ServiceBlacklist:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: dist/
      Handler: serverless.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          NODE_ENV: development
          APP_PORT: 3000
          PG_USER_NAME: pguser
          PG_PASS: pguser
          PG_DB: db
          PG_SCHEMA: public
          PG_HOST: host.docker.internal
          PG_PORT: 5432
      Events:
        Status:
          Type: Api
          Properties:
            Path: /status
            Method: get
        Blacklist:
          Type: Api
          Properties:
            Path: /blacklist
            Method: ANY
        BlacklistInternl:
          Type: Api
          Properties:
            Path: '/blacklist/{cpf}'
            Method: ANY
Outputs:
  BlackListApiProduction:
    Description: 'API Gateway endpoint URL for Prod stage for Blacklist function'
    Value: null
  ServiceBlacklist:
    Description: 'Hello World Lambda Function ARN'
    Value: null
  ServiceBlacklistIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: null
